
def WhitelistingScript(APNname,IP,netmask,MTXNum,SorD,pathToSave):
    # open output text file
    script = open(pathToSave + APNname + "_Script.txt", "a")
    script.write("TG GGSN12 & ZH GGSN13:\n")
    script.write("======================\n")
    script.write("save configuration /flash/configfiles/Before_Cororate_rulebase.cfg -redundant\n")
    script.write("config\n")
    script.write("active-charging service ecs \n")
    script.write("ruledef uctdapn_URLs-Match_009_090_99999\n")
    script.write("ip server-domain-name ends-with jnj-eg.ivycpg.com/web\n")
    script.write("ip server-domain-name ends-with jnj-eg.ivycpg.com/apps/Apk\n")
    script.write("ip server-domain-name ends-with s3-ap-southeast-1.amazonaws.com\n")
    script.write("ip server-domain-name ends-with myaccount.google.com/\n")
    script.write("ip server-domain-name contains jnj-eg.ivycpg.com\n")
    script.write("ip server-domain-name contains amazonaws.com\n")
    script.write("ip server-domain-name contains ap-southeast-1.elb.amazonaws.com\n")
    script.write("ip server-domain-name ends-with aws.amazon.com\n")
    script.write("ip server-domain-name ends-with amazon.com\n")
    script.write("ip server-domain-name ends-with awsstatic.com\n")
    script.write("ip server-domain-name contains awsstatic.com\n")
    script.write("multi-line-or all-lines\n")
    script.write("exit\n")
    script.write("ruledef Common-Browsing-URLs16_027_270_99999_USB_internet\n")
    script.write("ip server-domain-name ends-with Android.alezz-trade.com\n")
    script.write("ip server-domain-name ends-with powweb.com\n")
    script.write("ip server-domain-name ends-with alezz-trade.com\n")
    script.write("ip server-domain-name contains app.alezz-trade.com\n")
    script.write("ip server-domain-name ends-with riyada-eg.com\n")
    script.write("ip server-domain-name contains maps.google.com\n")
    script.write("ip server-domain-name contains i.ytimg.com\n")
    script.write("ip server-domain-name ends-with Sheets.google.com\n")
    script.write("ip server-domain-name ends-with Forms.google.com\n")
    script.write("ip server-domain-name ends-with Drive.google.com\n")
    script.write("ip server-domain-name ends-with Docs.google.com\n")
    script.write("ip server-domain-name ends-with *.alarabia-group.com\n")
    script.write("ip server-domain-name ends-with *.alezz-trade.com\n")
    script.write("ip server-domain-name ends-with *.gehazy.net\n")
    script.write("ip server-domain-name ends-with *.gehazy-eg.com\n")
    script.write("ip server-domain-name ends-with *.riyada-eg.com\n")
    script.write("ip server-domain-name ends-with bitrix24.net\n")
    script.write("ip server-domain-name ends-with storage.googleapis.com\n")
    script.write("ip server-domain-name ends-with mail.alarabia-group.com\n")
    script.write("ip server-domain-name contains powweb.com\n")
    script.write("ip server-domain-name contains .powweb.com\n")
    script.write("ip server-domain-name ends-with google.com\n")
    script.write("ip server-domain-name ends-with google.com/maps\n")
    script.write("ip server-domain-name contains google.com/maps\n")
    script.write("ip server-domain-name ends-with maps.gstatic.com\n")
    script.write("ip server-domain-name ends-with google.com/gen\n")
    script.write("ip server-domain-name ends-with play.google.com\n")
    script.write("ip server-domain-name ends-with lh3.googleusercontent.com\n")
    script.write("ip server-domain-name contains google.com\n")
    script.write("ip server-domain-name ends-with googlesyndication.com\n")
    script.write("ip server-domain-name ends-with ssl.gstatic.com\n")
    script.write("multi-line-or all-lines\n")
    script.write("exit\n")
    script.write("ruledef Common-Browsing-IPs2_027_270_99999_USB_internet\n")
    script.write("ip server-ip-address = 41.32.223.221/32\n")
    script.write("ip server-ip-address = 41.32.223.215/32\n")
    script.write("ip server-ip-address = 197.45.86.230/32\n")
    script.write("ip server-ip-address = 213.212.216.127/32\n")
    script.write("ip server-ip-address = 41.32.42.38/32\n")
    script.write("ip server-ip-address = 41.39.167.100/32\n")
    script.write("ip server-ip-address = 197.51.79.221/32\n")
    script.write("ip server-ip-address = 213.212.216.238/32\n")
    script.write("ip server-ip-address = 105.199.10.38/32\n")
    script.write("ip server-ip-address = 105.198.226.208/32\n")
    script.write("ip server-ip-address = 41.38.5.199/32\n")
    script.write("ip server-ip-address = 196.218.57.111/32\n")
    script.write("ip server-ip-address = 41.39.121.62/32\n")
    script.write("ip server-ip-address = 213.212.216.223/32\n")
    script.write("ip server-ip-address = 197.44.81.219/32\n")
    script.write("ip server-ip-address = 41.153.30.159/32\n")
    script.write("ip server-ip-address = 105.199.11.51/32\n")
    script.write("ip server-ip-address = 105.198.234.119/32\n")
    script.write("ip server-ip-address = 197.44.157.104/32\n")
    script.write("ip server-ip-address = 62.240.101.13/32\n")
    script.write("ip server-ip-address = 196.151.242.141/32\n")
    script.write("multi-line-or all-lines\n")
    script.write("exit \n")
    script.write("ruledef Common-Browsing-URLs18_027_270_99999_USB_internet\n")
    script.write("ip server-domain-name ends-with clients1.google.com\n")
    script.write("ip server-domain-name ends-with clients4.google.com\n")
    script.write("ip server-domain-name ends-with googleusercontent.com\n")
    script.write("ip server-domain-name ends-with worldposta.com\n")
    script.write("ip server-domain-name contains worldposta.com\n")
    script.write("ip server-domain-name contains ns2.caching.vfe-hosting.net\n")
    script.write("multi-line-or all-lines\n")
    script.write("exit \n")
    script.write("ruledef moe.gov.eg-domains\n")
    script.write("ip server-domain-name contains moe.gov.eg\n")
    script.write("ip server-domain-name contains netdna.bootstrapcdn.com\n")
    script.write("multi-line-or all-lines\n")
    script.write("exit\n")
    script.write("ruledef emis.gov.eg-domains\n")
    script.write("ip server-domain-name contains emis.gov.eg\n")
    script.write("ip server-domain-name contains dc.services.visualstudio.com\n")
    script.write("ip server-domain-name contains az416426.vo.msecnd.net\n")
    script.write("multi-line-or all-lines\n")
    script.write("exit\n")
    script.write("ruledef ekb.eg-domains\n")
    script.write("ip server-domain-name contains ekb.eg\n")
    script.write("ip server-domain-name contains certify.alexametrics.com\n")
    script.write("ip server-domain-name contains cloudfront-labs.amazonaws.com\n")
    script.write("ip server-domain-name contains cdnjs.cloudflare.com\n")
    script.write("multi-line-or all-lines\n")
    script.write("exit\n")
    script.write("ruledef elearning.moe.gov.eg-domains\n")
    script.write("ip server-domain-name contains elearning.moe.gov.eg\n")
    script.write("multi-line-or all-lines\n")
    script.write("exit\n")
    script.write("ruledef edraak.org-domains\n")
    script.write("ip server-domain-name contains edraak.org\n")
    script.write("ip server-domain-name contains static.zdassets.com\n")
    script.write("ip server-domain-name contains sc-static.net\n")
    script.write("ip server-domain-name contains tr.snapchat.com\n")
    script.write("ip server-domain-name contains ekr.zdassets.com\n")
    script.write("ip server-domain-name contains edraak-main.zendesk.com\n")
    script.write("multi-line-or all-lines\n")
    script.write("exit\n")
    script.write("ruledef discoveryeducation.ekb.eg-domains\n")
    script.write("ip server-domain-name contains discoveryeducation.ekb.eg\n")
    script.write("ip server-domain-name contains api-public.addthis.com\n")
    script.write("ip server-domain-name contains s7.addthis.com\n")
    script.write("ip server-domain-name contains v1.addthis.com\n")
    script.write("ip server-domain-name contains v1.addthisedge.com\n")
    script.write("ip server-domain-name contains tags.bluekai.com\n")
    script.write("ip server-domain-name contains a.tribalfusion.com\n")
    script.write("ip server-domain-name contains dpm.demdex.net\n")
    script.write("ip server-domain-name contains sync.crwdcntrl.net\n")
    script.write("multi-line-or all-lines\n")
    script.write("exit\n")
    script.write("ruledef schoolportal.moe.gov.eg-domains\n")
    script.write("ip server-domain-name contains schoolportal.moe.gov.eg\n")
    script.write("ip server-domain-name contains bam.nr-data.net\n")
    script.write("ip server-domain-name contains js-agent.newrelic.com/nr-1130.min.js\n")
    script.write("multi-line-or all-lines\n")
    script.write("exit\n")
    script.write("ruledef nafham.com-domains\n")
    script.write("ip server-domain-name contains nafham.com\n")
    script.write("ip server-domain-name contains i.ytimg.com\n")
    script.write("ip server-domain-name contains i1.ytimg.com\n")
    script.write("ip server-domain-name contains use.fontawesome.com\n")
    script.write("multi-line-or all-lines\n")
    script.write("exit\n")
    script.write("ruledef tahriracademy.org-domains\n")
    script.write("ip server-domain-name contains tahriracademy.org\n")
    script.write("ip server-domain-name contains ar.hao123.com\n")
    script.write("ip server-domain-name contains cdn.optimizely.com\n")
    script.write("multi-line-or all-lines\n")
    script.write("exit\n")
    script.write("ruledef portal.moe.gov.eg-domains\n")
    script.write("ip server-domain-name contains portal.moe.gov.eg\n")
    script.write("multi-line-or all-lines\n")
    script.write("exit\n")
    script.write("ruledef CommnURLS-Google-domains\n")
    script.write("ip server-domain-name contains fonts.googleapis.com\n")
    script.write("ip server-domain-name contains google-analytics.com\n")
    script.write("ip server-domain-name contains fonts.gstatic.com\n")
    script.write("ip server-domain-name contains khms1.googleapis.com\n")
    script.write("ip server-domain-name contains maps.googleapis.com\n")
    script.write("ip server-domain-name contains maps.gstatic.com\n")
    script.write("ip server-domain-name contains googletagmanager.com\n")
    script.write("ip server-domain-name contains googleads.g.doubleclick.net\n")
    script.write("ip server-domain-name contains googleadservices.com\n")
    script.write("ip server-domain-name contains bid.g.doubleclick.net\n")
    script.write("ip server-domain-name contains pagead2.googlesyndication.com\n")
    script.write("ip server-domain-name contains adservice.google.com\n")
    script.write("ip server-domain-name contains ajax.googleapis.com\n")
    script.write("ip server-domain-name contains apis.google.com\n")
    script.write("ip server-domain-name contains stats.g.doubleclick.net\n")
    script.write("ip server-domain-name contains accounts.google.com\n")
    script.write("ip server-domain-name contains ssl.gstatic.com\n")
    script.write("ip server-domain-name contains google.com.eg\n")
    script.write("multi-line-or all-lines\n")
    script.write("exit\n")
    script.write("ruledef teachersfirstegypt-domains\n")
    script.write("ip server-domain-name contains teachersfirstegypt.com\n")
    script.write("ip server-domain-name contains c51.968.myftpupload.com\n")
    script.write("ip server-domain-name contains amcharts.com\n")
    script.write("ip server-domain-name contains yt3.ggpht.com\n")
    script.write("multi-line-or all-lines\n")
    script.write("exit\n")
    script.write("ruledef assessment.ekb\n")
    script.write("ip server-domain-name contains assessment.ekb.eg\n")
    script.write("multi-line-or all-lines\n")
    script.write("exit\n")
    script.write("ruledef learnosity\n")
    script.write("ip server-domain-name contains learnosity.com\n")
    script.write("ip server-domain-name contains us-u.openx.net\n")
    script.write("ip server-domain-name contains pixel.rubiconproject.com\n")
    script.write("ip server-domain-name contains pi.pardot.com\n")
    script.write("ip server-domain-name contains p.adsymptotic.com\n")
    script.write("ip server-domain-name contains js.driftt.com\n")
    script.write("ip server-domain-name contains idsync.rlcdn.com\n")
    script.write("ip server-domain-name contains ib.adnxs.com\n")
    script.write("ip server-domain-name contains eb2.3lift.com\n")
    script.write("ip server-domain-name contains dsum-sec.casalemedia.com\n")
    script.write("ip server-domain-name contains d.adroll.com\n")
    script.write("multi-line-or all-lines\n")
    script.write("exit\n")
    script.write("ruledef MOE-Google-domains\n")
    script.write("ip server-domain-name contains fonts.googleapis.com\n")
    script.write("ip server-domain-name contains ajax.googleapis.com\n")
    script.write("ip server-domain-name contains fonts.gstatic.com\n")
    script.write("ip server-domain-name contains googleads.g.doubleclick.net\n")
    script.write("ip server-domain-name contains stats.g.doubleclick.net\n")
    script.write("ip server-domain-name contains lh3.googleusercontent.com\n")
    script.write("ip server-domain-name contains google-analytics.com\n")
    script.write("ip server-domain-name contains google.com\n")
    script.write("ip server-domain-name contains googleadservices.com\n")
    script.write("ip server-domain-name contains googletagmanager.com\n")
    script.write("ip server-domain-name contains maps.gstatic.com\n")
    script.write("ip server-domain-name contains gstatic.com\n")
    script.write("ip server-domain-name contains maps.googleapis.com\n")
    script.write("multi-line-or all-lines\n")
    script.write("exit\n")
    script.write("ruledef pegqa_domains\n")
    script.write("ip server-domain-name contains pegqa.school01.tuttiavn.com:8080/pearson\n")
    script.write("ip server-domain-name contains pegqa.school02.tuttiavn.com:8080/pearson\n")
    script.write("ip server-domain-name contains pegqa.central.tuttiavn.com:8080/pearson\n")
    script.write("ip server-domain-name contains pegqa.tuttiavn.com\n")
    script.write("multi-line-or all-lines\n")
    script.write("exit\n")
    script.write("ruledef KONE_Domains\n")
    script.write("ip server-domain-name contains messaging.internetofthings.ibmcloud.com\n")
    script.write("ip server-domain-name contains internetofthings.ibmcloud.com\n")
    script.write("ip server-domain-name contains uk.internetofthings.ibmcloud.com\n")
    script.write("ip server-domain-name contains internetofthings.chinabluemix.net\n")
    script.write("ip server-domain-name contains lon.objectstorage.open.softlayer.com\n")
    script.write("ip server-domain-name contains lon-identity.open.softlayer.com\n")
    script.write("ip server-domain-name contains s3.eu.cloud-object-storage.appdomain.cloud\n")
    script.write("ip server-domain-name contains s3.us-south.objectstorage.softlayer.net\n")
    script.write("ip server-domain-name contains time1.google.com\n")
    script.write("ip server-domain-name contains time2.google.com\n")
    script.write("ip server-domain-name contains time3.google.com\n")
    script.write("ip server-domain-name contains time4.google.com\n")
    script.write("ip server-domain-name contains time.google.com\n")
    script.write("ip server-domain-name contains pool.ntp.org\n")
    script.write("ip server-domain-name contains device-provisioning-test.kone.com\n")
    script.write("ip server-domain-name contains device-provisioning.kone.com\n")
    script.write("ip server-domain-name contains device-provisioning-cn.kone.com\n")
    script.write("ip server-domain-name contains device-provisioning-cn-uat.kone.com\n")
    script.write("ip server-domain-name contains s3.amazonaws.com\n")
    script.write("ip server-domain-name contains s3-eu-west-1.amazonaws.com\n")
    script.write("ip server-ip-address range host-pool KONE\n")
    script.write("multi-line-or all-lines\n")
    script.write("exit\n")
    script.write("ruledef KONE_Domains_1\n")
    script.write("ip server-domain-name contains s81c.com\n")
    script.write("ip server-domain-name contains a.idio.co\n")
    script.write("ip server-domain-name contains ad.crwdcntrl.net\n")
    script.write("ip server-domain-name contains bat.bing.com\n")
    script.write("ip server-domain-name contains bcp.crwdcntrl.net\n")
    script.write("ip server-domain-name contains cdn.segment.com/analytics.js\n")
    script.write("ip server-domain-name contains cloud.ibm.com\n")
    script.write("ip server-domain-name contains consent.trustarc.com/asset/notice-ibm.js\n")
    script.write("ip server-domain-name contains consent.truste.com\n")
    script.write("ip server-domain-name contains data.cmcore.com\n")
    script.write("ip server-domain-name contains data.coremetrics.com\n")
    script.write("ip server-domain-name contains googleads.g.doubleclick.net\n")
    script.write("ip server-domain-name contains js.idio.co/1474.js\n")
    script.write("ip server-domain-name contains libs.coremetrics.com\n")
    script.write("ip server-domain-name contains pixel.mathtag.com\n")
    script.write("ip server-domain-name contains s.idio.co/ia.js\n")
    script.write("ip server-domain-name contains script.hotjar.com\n")
    script.write("ip server-domain-name contains scripts.demandbase.com\n")
    script.write("ip server-domain-name contains static.hotjar.com\n")
    script.write("ip server-domain-name contains stats.g.doubleclick.net\n")
    script.write("ip server-domain-name contains sync.crwdcntrl.net\n")
    script.write("ip server-domain-name contains tags.crwdcntrl.net\n")
    script.write("ip server-domain-name contains tags.tiqcdn.com\n")
    script.write("ip server-domain-name contains tmscdn.coremetrics.com\n")
    script.write("ip server-domain-name contains visitor-service-eu-central-1.tealiumiq.com\n")
    script.write("ip server-domain-name contains www-api.ibm.com\n")
    script.write("ip server-domain-name contains google-analytics.com\n")
    script.write("ip server-domain-name contains google.com\n")
    script.write("ip server-domain-name contains googleadservices.com\n")
    script.write("ip server-domain-name contains googletagmanager.com\n")
    script.write("multi-line-or all-lines\n")
    script.write("exit\n")
    script.write("ruledef Mars_IPs\n")
    script.write("ip server-ip-address = 13.76.93.162/32\n")
    script.write("ip server-ip-address = 40.90.184.136/32\n")
    script.write("ip server-ip-address = 118.144.79.231/32\n")
    script.write("ip server-ip-address = 216.58.215.110/32\n")
    script.write("ip server-ip-address = 216.58.198.46/32\n")
    script.write("ip server-ip-address = 172.217.23.110/32\n")
    script.write("ip server-domain-name contains download.winmdm.com\n")
    script.write("multi-line-or all-lines\n")
    script.write("exit\n")
    script.write("ruledef GoogleMaps-Match_057_570_99999\n")
    script.write("p2p protocol = googlemaps\n")
    script.write("ip server-domain-name contains maps.google.com\n")
    script.write("ip server-domain-name ends-with .google.com\n")
    script.write("ip server-domain-name contains googleapis.com\n")
    script.write("ip server-domain-name contains maps.gstatic.com\n")
    script.write("ip server-domain-name contains www.gstatic.com\n")
    script.write("ip server-domain-name ends-with www.google.com/\n")
    script.write("ip server-domain-name contains www.google.com\n")
    script.write("ip server-domain-name contains google.com/maps\n")
    script.write("multi-line-or all-lines\n")
    script.write("exit\n")
    script.write("ruledef AAIB_URLs\n")
    script.write("ip server-domain-name ends-with Ngpos-uat.network.ae\n")
    script.write("ip server-domain-name ends-with Ngpos.network.ae\n")
    script.write("ip server-domain-name ends-with Ngpos-preprod.network.ae\n")
    script.write("multi-line-or all-lines\n")
    script.write("exit\n")
    script.write("group-of-ruledefs uctdapn_URLs_009_090_99999\n")
    script.write("add-ruledef priority 10 ruledef GoogleMaps-Match_057_570_99999\n")
    script.write("add-ruledef priority 20 ruledef uctdapn_URLs-Match_009_090_99999\n")
    script.write("exit\n")
    script.write("group-of-ruledefs URLs-Match_009_090_99999\n")
    script.write("add-ruledef priority 10 ruledef Common-Browsing-URLs16_027_270_99999_USB_internet\n")
    script.write("add-ruledef priority 20 ruledef Common-Browsing-IPs2_027_270_99999_USB_internet\n")
    script.write("add-ruledef priority 30 ruledef Common-Browsing-URLs18_027_270_99999_USB_internet\n")
    script.write("exit\n")
    script.write("group-of-ruledefs wfp.moe_URLs_009_090_00064\n")
    script.write("add-ruledef priority 10 ruledef moe.gov.eg-domains\n")
    script.write("add-ruledef priority 20 ruledef emis.gov.eg-domains\n")
    script.write("add-ruledef priority 30 ruledef ekb.eg-domains\n")
    script.write("add-ruledef priority 40 ruledef elearning.moe.gov.eg-domains\n")
    script.write("add-ruledef priority 50 ruledef edraak.org-domains\n")
    script.write("add-ruledef priority 60 ruledef discoveryeducation.ekb.eg-domains\n")
    script.write("add-ruledef priority 70 ruledef schoolportal.moe.gov.eg-domains\n")
    script.write("add-ruledef priority 80 ruledef nafham.com-domains\n")
    script.write("add-ruledef priority 90 ruledef tahriracademy.org-domains\n")
    script.write("add-ruledef priority 100 ruledef portal.moe.gov.eg-domains\n")
    script.write("add-ruledef priority 110 ruledef CommnURLS-Google-domains\n")
    script.write("add-ruledef priority 120 ruledef teachersfirstegypt-domains\n")
    script.write("exit\n")
    script.write("group-of-ruledefs wfp.moe_URLs_009_090_99999\n")
    script.write("add-ruledef priority 10 ruledef moe.gov.eg-domains\n")
    script.write("add-ruledef priority 20 ruledef emis.gov.eg-domains\n")
    script.write("add-ruledef priority 30 ruledef ekb.eg-domains\n")
    script.write("add-ruledef priority 40 ruledef elearning.moe.gov.eg-domains\n")
    script.write("add-ruledef priority 50 ruledef edraak.org-domains\n")
    script.write("add-ruledef priority 60 ruledef discoveryeducation.ekb.eg-domains\n")
    script.write("add-ruledef priority 70 ruledef schoolportal.moe.gov.eg-domains\n")
    script.write("add-ruledef priority 80 ruledef nafham.com-domains\n")
    script.write("add-ruledef priority 90 ruledef tahriracademy.org-domains\n")
    script.write("add-ruledef priority 100 ruledef portal.moe.gov.eg-domains\n")
    script.write("add-ruledef priority 110 ruledef CommnURLS-Google-domains\n")
    script.write("add-ruledef priority 120 ruledef teachersfirstegypt-domains\n")
    script.write("exit\n")
    script.write("group-of-ruledefs MOE_URLs_009_090_00064\n")
    script.write("add-ruledef priority 10 ruledef assessment.ekb\n")
    script.write("add-ruledef priority 20 ruledef learnosity\n")
    script.write("add-ruledef priority 30 ruledef MOE-Google-domains\n")
    script.write("add-ruledef priority 40 ruledef pegqa_domains\n")
    script.write("exit\n")
    script.write("group-of-ruledefs MOE_URLs_009_090_99999\n")
    script.write("add-ruledef priority 10 ruledef assessment.ekb\n")
    script.write("add-ruledef priority 20 ruledef learnosity\n")
    script.write("add-ruledef priority 30 ruledef MOE-Google-domains\n")
    script.write("add-ruledef priority 40 ruledef pegqa_domains\n")
    script.write("exit\n")
    script.write("group-of-ruledefs KONE_Domains_009_090_00064\n")
    script.write("add-ruledef priority 10 ruledef KONE_Domains\n")
    script.write("add-ruledef priority 20 ruledef KONE_Domains_1\n")
    script.write("exit\n")
    script.write("group-of-ruledefs Mars_URLs_009_090_00064\n")
    script.write("add-ruledef priority 10 ruledef Mars_IPs\n")
    script.write("add-ruledef priority 20 ruledef GoogleMaps-Match_057_570_99999\n")
    script.write("exit\n")
    script.write("group-of-ruledefs Mars_URLs_009_090_99999\n")
    script.write("add-ruledef priority 10 ruledef Mars_IPs\n")
    script.write("add-ruledef priority 20 ruledef GoogleMaps-Match_057_570_99999\n")
    script.write("exit\n")
    script.write("group-of-ruledefs KONE_Domains_009_090_99999\n")
    script.write("add-ruledef priority 10 ruledef KONE_Domains\n")
    script.write("add-ruledef priority 20 ruledef KONE_Domains_1\n")
    script.write("exit\n")
    script.write("group-of-ruledefs AAIB_009_090_00064\n")
    script.write("add-ruledef priority 10 ruledef AAIB_URLs\n")
    script.write("exit\n")
    script.write("group-of-ruledefs AAIB_009_090_99999\n")
    script.write("add-ruledef priority 10 ruledef AAIB_URLs\n")
    script.write("exit\n")
    script.write("ruledef allip_888_888_99999_Block\n")
    script.write("ip any-match = TRUE\n")
    script.write("exit\n")
    script.write("charging-action discard_traffic\n")
    script.write("flow action discard downlink\n")
    script.write("exit\n")
    script.write("config\n")
    script.write("active-charging service ecs\n")
    script.write("rulebase corporate-internet\n")
    script.write("dynamic-rule order always-first\n")
    script.write("tcp mss 1300 limit-if-present add-if-not-present\n")
    script.write("egcdr tariff minute 0 hour 0\n")
    script.write("billing-records egcdr\n")
    script.write(
        "action priority 850 dynamic-only ruledef TCPInit-missing_099_190_99999 charging-action discard_sid_099_rg_190_rate_99999\n")
    script.write(
        "action priority 900 dynamic-only group-of-ruledefs Signalling2_099_190_99999 charging-action nocc-sid_099_rg_190_rate_99999\n")
    script.write(
        "action priority 901 dynamic-only group-of-ruledefs TCPInit-sig_099_190_99999 charging-action nocc-sid_099_rg_190_rate_99999\n")
    script.write(
        "action priority 950 dynamic-only group-of-ruledefs uctdapn_URLs_009_090_99999 charging-action sid_009_rg_090_rate_99999\n")
    script.write(
        "action priority 1000 dynamic-only group-of-ruledefs URLs-Match_009_090_99999 charging-action sid_009_rg_090_rate_99999\n")
    script.write(
        "action priority 1100 dynamic-only group-of-ruledefs wfp.moe_URLs_009_090_00064 charging-action sid_009_rg_090_rate_00064\n")
    script.write(
        "action priority 1200 dynamic-only group-of-ruledefs wfp.moe_URLs_009_090_99999 charging-action sid_009_rg_090_rate_99999\n")
    script.write(
        "action priority 1300 dynamic-only group-of-ruledefs MOE_URLs_009_090_00064 charging-action sid_009_rg_090_rate_00064\n")
    script.write(
        "action priority 1350 dynamic-only group-of-ruledefs MOE_URLs_009_090_99999 charging-action sid_009_rg_090_rate_99999\n")
    script.write(
        "action priority 1400 dynamic-only group-of-ruledefs KONE_Domains_009_090_00064 charging-action sid_009_rg_090_rate_00064\n")
    script.write(
        "action priority 1420 dynamic-only group-of-ruledefs Mars_URLs_009_090_00064 charging-action sid_009_rg_090_rate_00064\n")
    script.write(
        "action priority 1430 dynamic-only group-of-ruledefs Mars_URLs_009_090_99999 charging-action sid_009_rg_090_rate_99999\n")
    script.write(
        "action priority 1450 dynamic-only group-of-ruledefs KONE_Domains_009_090_99999 charging-action sid_009_rg_090_rate_99999\n")
    script.write(
        "action priority 1455 dynamic-only group-of-ruledefs AAIB_009_090_00064 charging-action sid_009_rg_090_rate_00064\n")
    script.write(
        "action priority 1460 dynamic-only group-of-ruledefs AAIB_009_090_99999 charging-action sid_009_rg_090_rate_99999\n")
    script.write(
        "action priority 9998 dynamic-only ruledef allip_888_888_99999_Block charging-action discard_traffic\n")
    script.write(
        "action priority 9999 ruledef AllTraffic_009_090_99999_ALL_Corporate charging-action sid_009_rg_090_Corporate\n")
    script.write("route priority 10 ruledef LooksLike_DNS analyzer dns\n")
    script.write("route priority 20 ruledef LooksLike_HTTP_or_WAP2 analyzer http\n")
    script.write("flow limit-across-applications 5000\n")
    script.write("flow http max-packets-for-header-completion 10 action continue\n")
    script.write("flow control-handshaking charge-to-application mid-session-packets tear-down-packets\n")
    script.write("egcdr threshold interval 900\n")
    script.write("egcdr threshold volume total 4000000\n")
    script.write("cca quota retry-time 120\n")
    script.write("exit\n")
    script.write("end \n")
    script.write("Check point TG GGSN12: save configuration /flash/configfiles/TG2-GGSN-running.cfg\n")
    script.write("Check point ZH GGSN13: save configuration /flash/configfiles/ZH13-GGSN-config.cfg\n")
    script.write(
        "///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////\n")
    script.write("Rollback:\n")
    script.write("=========\n")
    script.write("TG GGSN12 & ZH GGSN13:\n")
    script.write("======================\n")
    script.write("save configuration /flash/configfiles/Before_Rollback_Cororate_rulebase.cfg -redundant\n")
    script.write("config\n")
    script.write("active-charging service ecs \n")
    script.write("no ruledef uctdapn_URLs-Match_009_090_99999\n")
    script.write("no ruledef Common-Browsing-URLs16_027_270_99999_USB_internet\n")
    script.write("no ruledef Common-Browsing-IPs2_027_270_99999_USB_internet\n")
    script.write("no ruledef Common-Browsing-URLs18_027_270_99999_USB_internet\n")
    script.write("no ruledef moe.gov.eg-domains\n")
    script.write("no ruledef emis.gov.eg-domains\n")
    script.write("no ruledef ekb.eg-domains\n")
    script.write("no ruledef elearning.moe.gov.eg-domains\n")
    script.write("no ruledef edraak.org-domains\n")
    script.write("no ruledef discoveryeducation.ekb.eg-domains\n")
    script.write("no ruledef schoolportal.moe.gov.eg-domains\n")
    script.write("no ruledef nafham.com-domains\n")
    script.write("no ruledef tahriracademy.org-domains\n")
    script.write("no ruledef portal.moe.gov.eg-domains\n")
    script.write("no ruledef CommnURLS-Google-domains\n")
    script.write("no ruledef teachersfirstegypt-domains\n")
    script.write("no ruledef assessment.ekb\n")
    script.write("no ruledef learnosity\n")
    script.write("no ruledef MOE-Google-domains\n")
    script.write("no ruledef pegqa_domains\n")
    script.write("no ruledef KONE_Domains\n")
    script.write("no ruledef KONE_Domains_1\n")
    script.write("no ruledef Mars_IPs\n")
    script.write("no ruledef GoogleMaps-Match_057_570_99999\n")
    script.write("no ruledef AAIB_URLs\n")
    script.write("no group-of-ruledefs uctdapn_URLs_009_090_99999\n")
    script.write("no group-of-ruledefs URLs-Match_009_090_99999\n")
    script.write("no group-of-ruledefs wfp.moe_URLs_009_090_00064 \n")
    script.write("no group-of-ruledefs wfp.moe_URLs_009_090_99999\n")
    script.write("no group-of-ruledefs MOE_URLs_009_090_00064\n")
    script.write("no group-of-ruledefs MOE_URLs_009_090_99999\n")
    script.write("no group-of-ruledefs KONE_Domains_009_090_00064 \n")
    script.write("no group-of-ruledefs Mars_URLs_009_090_00064 \n")
    script.write("no group-of-ruledefs Mars_URLs_009_090_99999\n")
    script.write("no group-of-ruledefs KONE_Domains_009_090_99999\n")
    script.write("no group-of-ruledefs AAIB_009_090_00064 \n")
    script.write("no group-of-ruledefs AAIB_009_090_99999 \n")
    script.write("no ruledef allip_888_888_99999_Block\n")
    script.write("no charging-action discard_traffic\n")
    script.write("no rulebase corporate-internet\n")
    script.write("exit\n")
    script.write("end \n")
    script.write("Check point TG GGSN12: save configuration /flash/configfiles/TG2-GGSN-running.cfg\n")
    script.write("Check point ZH GGSN13: save configuration /flash/configfiles/ZH13-GGSN-config.cfg\n")
    script.write("\n")











    script.close()