def SecPC_Connectivity_Script (APN_Name, Src_Tunnel_Fixed, pathToSave ):

    script = open(pathToSave + APN_Name + "_Script.txt", "w")
    script.write('APN' + APN_Name + '\n')
    script.write('On PIX firewall'  + ':\n')
    script.write('---------------' + '\n')
    script.write('set address "outside" " '+APN_Name+ ' APN Tunnel-End"' +Src_Tunnel_Fixed+ '\n')
    script.write('set policy top name "' +APN_Name+ 'APN" from "outside" to "Corp_GPRS"  "'+APN_Name+' APN Tunnel-End" "NEW_TGGGSN12_Loopback" "GRE" permit log  \n')
    script.write('set policy id  \n')
    script.write('set service "PING"  \n')
    script.write('exit \n')
    script.write('set policy top  name "'+APN_Name+ 'APN" from "Corp_GPRS" to "outside"  "NEW_TGGGSN12_Loopback" "'+APN_Name+' APN Tunnel-End" "GRE" permit log  \n')
    script.write('set policy id  \n')
    script.write('set service "PING"  \n')
    script.write('exit \n')
    script.write('set route' +Src_Tunnel_Fixed+ 'interface ethernet3/2 gateway 192.168.151.200 \n')
    script.write('save \n')
    script.write('---------------------------------------------------------------\n')
    script.write('\n \n')
    script.write('Rollback\n')
    script.write('=========\n \n')
    script.write('PIX firewall\n')
    script.write('=========\n')
    script.write('\n \n')
    script.write('unset address "outside" "'+APN_Name+' APN Tunnel-End" 10.215.122.112/32 \n')
    script.write('unset policy id  \n')
    script.write('unset policy id  \n')
    script.write('unset route' +Src_Tunnel_Fixed+ 'interface ethernet3/2 gateway 192.168.151.200 \n')
